export const FINANZAS_STEPS = [
  {
    id: 'intro',
    title: 'Tus finanzas en Kudi',
    message: 'Aquí ves cómo va tu negocio: ventas, gastos y ganancias. Todo automático con cada venta que registras.',
    expression: 'eureka',
    position: 'center',
    route: '/pl',
  },
  {
    id: 'timeline',
    title: 'Tu Timeline',
    message: 'El Timeline muestra TODAS tus transacciones del mes: ventas (verde), compras (ámbar) y gastos (rojo). Es tu bitácora financiera.',
    expression: 'atencion',
    position: 'center',
    route: '/pl',
  },
  {
    id: 'registrar',
    title: 'Registra movimientos',
    message: 'Desde aquí también puedes registrar ventas, compras y gastos manualmente con el botón "+ Registrar".',
    expression: 'todoBien',
    position: 'center',
    route: '/pl',
    allowInteraction: true,
  },
  {
    id: 'resumen',
    title: 'Estado de resultados',
    message: 'Esta es tu foto financiera: cuánto vendes, cuánto te cuesta y cuánto ganas. Los KPIs de arriba te dan el resumen rápido.',
    expression: 'eureka',
    position: 'center',
    route: '/pl/resumen',
  },
  {
    id: 'cashflow',
    title: 'Flujo de caja',
    message: 'Aquí ves mes a mes cuánto entra y sale. Ideal para planificar y saber si necesitas capital.',
    expression: 'pensando',
    position: 'center',
    route: '/pl/cashflow',
  },
  {
    id: 'done',
    title: '¡Ya dominas Kudi!',
    message: 'Conoces lo esencial: costear, vender y ver tus finanzas. Explora los demás módulos a tu ritmo. ¡Éxitos con tu negocio!',
    expression: 'celebrando',
    position: 'center',
    action: { label: 'Volver al inicio →', route: '/dashboard' },
  },
];
