export const MATERIALES_STEPS = [
  {
    id: 'intro',
    title: 'Registra tus materiales',
    message: 'Los materiales son todo lo que usas para empacar: cajas, bolsas, etiquetas, cintas...',
    expression: 'atencion',
    position: 'center',
    route: '/materiales',
  },
  {
    id: 'click-nuevo',
    target: '#btn-nuevo-material',
    title: 'Crea tu primer material',
    message: 'Haz clic para agregar un material de empaque.',
    expression: 'eureka',
    position: 'bottom',
    route: '/materiales',
    waitFor: 'click',
  },
  {
    id: 'fill-data',
    target: '#material-nombre',
    title: 'Llena los datos del material',
    message: 'Te puse un ejemplo: Caja kraft, 50 unidades a S/ 25.00 (S/ 0.50 c/u). Cámbialo si quieres.',
    expression: 'todoBien',
    position: 'bottom',
    allowInteraction: true,
    prefill: {
      '#material-nombre': 'Caja kraft',
      '#material-cantidad': '50',
      '#material-precio': '25.00',
    },
  },
  {
    id: 'save-hint',
    target: '#material-save',
    title: 'Guarda el material',
    message: 'Haz clic para registrarlo.',
    expression: 'eureka',
    position: 'top',
    waitFor: 'click',
  },
  {
    id: 'done',
    title: '¡Materiales listos!',
    message: 'Ya tienes ingredientes y materiales. ¡Ahora sí, a crear tu primer producto!',
    expression: 'celebrando',
    position: 'center',
    action: { label: 'Crear mi primer producto →', route: '/cotizador' },
  },
];
